### ISSUE TITLE
MBLS1028A Device Tree wrong pin for signal DCDC_RESET

### ISSUE THREAD

**Issue by Georges760** [tq-systems/linux-tqmaxx#2]
As per the MBLS1028A.SP.0103 schematic, the signal DCDC_RESET is wired on the 1V8 GPIO Expander IO_6 :

![image](https://user-images.githubusercontent.com/1989461/193041716-b82d680e-e343-41ab-a41c-58f20bc6865a.png)

But on the DTS definition it is mapped on the gpio 7 :
https://github.com/tq-systems/linux-tqmaxx/blob/0d4bcc6c5bcb9f79d3459257716ed53be62909dc/arch/arm64/boot/dts/freescale/fsl-ls1028a-mbls1028a.dts#L108

**Comment by tq-niebelm** [comment]
@gregorHerburger Is this on your screen?

**Comment by tq-niebelm** [comment]
@gregorHerburger Is this already fixed?

**Comment by tq-gregorHerburger** [comment]
Fixed with https://github.com/tq-systems/linux-tqmaxx/commit/70ddbf9e156f634743838a564873dfd39bd8bc8a
